name: 02 - Workflow Events
on:
  push:
  workflow_dispatch:
  
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Event trigger ${{ github.event_name }}" + "${{ github.event_name }}"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I"
          echo "will"
          echo "fail."
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye, new World!"