name: 06 - Contexts
run-name: 06 - Contexts |   DEBUG - ${{inputs.debug}}
on:
  push:
  workflow_dispatch:
    inputs:
        debug:
            type: boolean
            default: false

env:
  MY_VAR: "This is a variable from the env section"
  MY_VAR2: "This is another variable from the env section"

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "This is a variable from the job env section"
      MY_VAR2: "This is another variable from the job env section"
    steps:
      - name: Display information
        run: |
            echo "The event that triggered this workflow is ${{ github.event_name }}"
            echo "The ref is ${{ github.ref }}"
            echo "The sha is ${{ github.sha }}"
            echo "The actor is ${{ github.actor }}"
            echo "The workflow is ${{ github.workflow }}"
            echo "the run id is ${{ github.run_id }}"
            echo "the run number is ${{ github.run_number }}"
      - name: Retrieve Variables
        run: |
            echo "The variable value is ${{vars.MY_VAR}}"
      - name: Display variables from env section
        env:
          MY_VAR: "This is a overwritten from the step env section"
        run: |
            echo "The variable value is ${{env.MY_VAR}}"
            echo "The variable value is ${{env.MY_VAR2}}"