name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Skip deployment steps and only print the commands that would be executed
        default: false
      target:
        type: environment
        required: true
        description: The target environment for deployment
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: The version tag to deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "building from tag ${{ inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }}